---
  - name: "install dependencies."
    become: true
    apt:
      name: "tar"
      state: latest
      update_cache: yes

  - name: Create a directory if it does not exist
    become: true
    ansible.builtin.file:
    path: /home/ubuntu/backend
    state: directory
    mode: '0755'

  # - name: Copy backend dist files to remote server
  #   copy:
  #     src: /root/project/backend
  #     dest: /home/ubuntu
  - name: "copy folder "
    become: true
    copy:
      #src: /root/project/backend/dist
      src: /root/project/artifact.tar.gz
      #src: /root/project/
      dest: /home/ubuntu/

  - name: "untar folder "
    become: true
    ansible.builtin.unarchive:
      #src: /root/project/backend/dist
      src: /home/ubuntu/artifact.tar.gz
      #src: /root/project/
      dest: /home/ubuntu/backend/
      remote_src: yes

  - name: Install Node modules
    shell: |
      cd /home/ubuntu/backend
      npm install

  - name: Building backend
    shell: |
      cd /home/ubuntu/backend
      npm i
      npm run build

  - name: Start pm2 service
    shell: |
      cd /home/ubuntu/backend
      pm2 start npm --name backend -- start
