---
  - name: Copy backend dist files to remote server
    copy:
      src: /root/project/backend
      dest: /home/ubuntu

  - name: Building backend
    shell: 
      chdir: ~/backend
      cmd: npm run build

  - name: Run app
    shell: 
      chdir: ~/backend
      cmd: pm2 start ./dist/main.js

  - name: Configure pm2
    shell: |
      eval $(pm2 startup | tail -1)\n\
      pm2 save
