---
  - name: "install dependencies."
    become: true
    apt:
      name: "tar"
      state: latest
      update_cache: yes


  # - name: Copy backend dist files to remote server
  #   copy:
  #     src: /root/project/backend
  #     dest: /home/ubuntu
  - name: "copy tar file "
    become: true
    copy:
      #src: /root/project/backend/dist
      src: /root/project/artifact.tar.gz
      #src: /root/project/
      dest: /home/ubuntu/

  - name: "Untar backend folder"
    become: true
    shell: |
      cd /home/ubuntu/
      tar -xzvf artifact.tar.gz

  - name: Install Node modules
    shell: |
      cd /home/ubuntu/backend
      npm i

  - name: Building backend
    shell: |
      cd /home/ubuntu/backend
      npm run build

  - name: Start pm2 service
    shell: |
      cd /home/ubuntu/backend
      pm2 start npm --name backend -- start
